# Generated by Django 4.2.13 on 2024-07-01 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_budget_user_expense_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='user',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='user',
        ),
    ]
