# Generated by Django 4.2.13 on 2024-07-01 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_budget_user_expense_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='alert_sent',
            field=models.BooleanField(default=False),
        ),
    ]
